### YamlMime:ManagedReference
items:
- uid: Mono.Security.Protocol.Ntlm.NtlmSettings
  commentId: T:Mono.Security.Protocol.Ntlm.NtlmSettings
  id: NtlmSettings
  children:
  - Mono.Security.Protocol.Ntlm.NtlmSettings.DefaultAuthLevel
  langs:
  - csharp
  name: NtlmSettings
  nameWithType: NtlmSettings
  fullName: Mono.Security.Protocol.Ntlm.NtlmSettings
  type: Class
  assemblies:
  - System
  namespace: Mono.Security.Protocol.Ntlm
  syntax:
    content: public static class NtlmSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - xamarinandroid-7.1
  - xamarinios-10.8
  monikers:
  - xamarinandroid-7.1
  - xamarinios-10.8
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/Mono.Security.Protocol.Ntlm/NtlmSettings.xml
- uid: Mono.Security.Protocol.Ntlm.NtlmSettings.DefaultAuthLevel
  commentId: P:Mono.Security.Protocol.Ntlm.NtlmSettings.DefaultAuthLevel
  id: DefaultAuthLevel
  parent: Mono.Security.Protocol.Ntlm.NtlmSettings
  langs:
  - csharp
  name: DefaultAuthLevel
  nameWithType: NtlmSettings.DefaultAuthLevel
  fullName: NtlmSettings.DefaultAuthLevel
  type: Property
  assemblies:
  - System
  namespace: Mono.Security.Protocol.Ntlm
  syntax:
    content: public static Mono.Security.Protocol.Ntlm.NtlmAuthLevel DefaultAuthLevel { get; set; }
    return:
      type: Mono.Security.Protocol.Ntlm.NtlmAuthLevel
      description: ''
  overload: Mono.Security.Protocol.Ntlm.NtlmSettings.DefaultAuthLevel*
  exceptions: []
  version:
  - xamarinandroid-7.1
  - xamarinios-10.8
  monikers:
  - xamarinandroid-7.1
  - xamarinios-10.8
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/Mono.Security.Protocol.Ntlm/NtlmSettings.xml
references:
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Mono.Security.Protocol.Ntlm.NtlmSettings.DefaultAuthLevel
  parent: Mono.Security.Protocol.Ntlm.NtlmSettings
  isExternal: false
  name: DefaultAuthLevel
  nameWithType: NtlmSettings.DefaultAuthLevel
  fullName: NtlmSettings.DefaultAuthLevel
- uid: Mono.Security.Protocol.Ntlm.NtlmAuthLevel
  parent: Mono.Security.Protocol.Ntlm
  isExternal: false
  name: NtlmAuthLevel
  nameWithType: NtlmAuthLevel
  fullName: Mono.Security.Protocol.Ntlm.NtlmAuthLevel
- uid: Mono.Security.Protocol.Ntlm.NtlmSettings.DefaultAuthLevel*
  parent: Mono.Security.Protocol.Ntlm.NtlmSettings
  isExternal: false
  name: DefaultAuthLevel
  nameWithType: NtlmSettings.DefaultAuthLevel
  fullName: NtlmSettings.DefaultAuthLevel
  monikers:
  - xamarinandroid-7.1
  - xamarinios-10.8
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/Mono.Security.Protocol.Ntlm/NtlmSettings.xml
- uid: System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: false
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: Object.Equals(Object)
- uid: System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: false
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: Object.Equals(Object, Object)
- uid: System.Object.GetHashCode
  parent: System.Object
  isExternal: false
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: Object.GetHashCode()
- uid: System.Object.GetType
  parent: System.Object
  isExternal: false
  name: GetType()
  nameWithType: Object.GetType()
  fullName: Object.GetType()
- uid: System.Object.MemberwiseClone
  parent: System.Object
  isExternal: false
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: Object.MemberwiseClone()
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: false
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: Object.ReferenceEquals(Object, Object)
- uid: System.Object.ToString
  parent: System.Object
  isExternal: false
  name: ToString()
  nameWithType: Object.ToString()
  fullName: Object.ToString()
