### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.PeerSecuritySettings
  commentId: T:System.ServiceModel.PeerSecuritySettings
  id: PeerSecuritySettings
  children:
  - System.ServiceModel.PeerSecuritySettings.#ctor
  - System.ServiceModel.PeerSecuritySettings.Mode
  - System.ServiceModel.PeerSecuritySettings.ShouldSerializeMode
  - System.ServiceModel.PeerSecuritySettings.ShouldSerializeTransport
  - System.ServiceModel.PeerSecuritySettings.Transport
  langs:
  - csharp
  name: PeerSecuritySettings
  nameWithType: PeerSecuritySettings
  fullName: System.ServiceModel.PeerSecuritySettings
  type: Class
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: Contains the security settings associated with a peer channel, including the type of authentication used and the security used for the message transport.
  syntax:
    content: public sealed class PeerSecuritySettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel/PeerSecuritySettings.xml
  ms.technology:
  - dotnet-standard
  manager: ghogen
- uid: System.ServiceModel.PeerSecuritySettings.#ctor
  commentId: M:System.ServiceModel.PeerSecuritySettings.#ctor
  id: '#ctor'
  parent: System.ServiceModel.PeerSecuritySettings
  langs:
  - csharp
  name: PeerSecuritySettings()
  nameWithType: PeerSecuritySettings.PeerSecuritySettings()
  fullName: PeerSecuritySettings.PeerSecuritySettings()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: Initializes a new default instance of the <xref href="System.ServiceModel.PeerSecuritySettings"></xref> class.
  syntax:
    content: public PeerSecuritySettings ();
    parameters: []
  overload: System.ServiceModel.PeerSecuritySettings.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel/PeerSecuritySettings.xml
  ms.technology:
  - dotnet-standard
  manager: ghogen
- uid: System.ServiceModel.PeerSecuritySettings.Mode
  commentId: P:System.ServiceModel.PeerSecuritySettings.Mode
  id: Mode
  parent: System.ServiceModel.PeerSecuritySettings
  langs:
  - csharp
  name: Mode
  nameWithType: PeerSecuritySettings.Mode
  fullName: PeerSecuritySettings.Mode
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: Gets and sets the value that indicates the security mode of the peer channel.
  syntax:
    content: public System.ServiceModel.SecurityMode Mode { get; set; }
    return:
      type: System.ServiceModel.SecurityMode
      description: <xref href="System.ServiceModel.SecurityMode"></xref> enumeration value that indicates the security mode for the peer channel.
  overload: System.ServiceModel.PeerSecuritySettings.Mode*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: The specified value is not an enumerated value from <xref href="System.ServiceModel.SecurityMode"></xref>
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel/PeerSecuritySettings.xml
  ms.technology:
  - dotnet-standard
  manager: ghogen
- uid: System.ServiceModel.PeerSecuritySettings.ShouldSerializeMode
  commentId: M:System.ServiceModel.PeerSecuritySettings.ShouldSerializeMode
  id: ShouldSerializeMode
  parent: System.ServiceModel.PeerSecuritySettings
  langs:
  - csharp
  name: ShouldSerializeMode()
  nameWithType: PeerSecuritySettings.ShouldSerializeMode()
  fullName: PeerSecuritySettings.ShouldSerializeMode()
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: Gets a value that indicates whether the security mode information should be serialized.
  syntax:
    content: public bool ShouldSerializeMode ();
    parameters: []
    return:
      type: System.Boolean
      description: Returns <xref href="System.Boolean"></xref> that specifies `true` if the security mode information should be serialized, and `false` if it should not be serialized..
  overload: System.ServiceModel.PeerSecuritySettings.ShouldSerializeMode*
  exceptions: []
  attributes: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel/PeerSecuritySettings.xml
  ms.technology:
  - dotnet-standard
  manager: ghogen
- uid: System.ServiceModel.PeerSecuritySettings.ShouldSerializeTransport
  commentId: M:System.ServiceModel.PeerSecuritySettings.ShouldSerializeTransport
  id: ShouldSerializeTransport
  parent: System.ServiceModel.PeerSecuritySettings
  langs:
  - csharp
  name: ShouldSerializeTransport()
  nameWithType: PeerSecuritySettings.ShouldSerializeTransport()
  fullName: PeerSecuritySettings.ShouldSerializeTransport()
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: Gets a value that indicates whether the transport information should be serialized.
  syntax:
    content: public bool ShouldSerializeTransport ();
    parameters: []
    return:
      type: System.Boolean
      description: Returns <xref href="System.Boolean"></xref> that specifies `true` if the transport information should be serialized, and `false` if it should not be serialized..
  overload: System.ServiceModel.PeerSecuritySettings.ShouldSerializeTransport*
  exceptions: []
  attributes: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel/PeerSecuritySettings.xml
  ms.technology:
  - dotnet-standard
  manager: ghogen
- uid: System.ServiceModel.PeerSecuritySettings.Transport
  commentId: P:System.ServiceModel.PeerSecuritySettings.Transport
  id: Transport
  parent: System.ServiceModel.PeerSecuritySettings
  langs:
  - csharp
  name: Transport
  nameWithType: PeerSecuritySettings.Transport
  fullName: PeerSecuritySettings.Transport
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: Gets the value that indicates the security settings for the transport used for messages transmitted over the peer channel.
  remarks: This property is set only if <xref:System.ServiceModel.PeerSecuritySettings.Mode%2A> is set to <xref:System.ServiceModel.SecurityMode.Transport> or <xref:System.ServiceModel.SecurityMode.TransportWithMessageCredential>.
  syntax:
    content: public System.ServiceModel.PeerTransportSecuritySettings Transport { get; set; }
    return:
      type: System.ServiceModel.PeerTransportSecuritySettings
      description: <xref href="System.ServiceModel.PeerTransportSecuritySettings"></xref> that contains the transport security settings for the peer channel.
  overload: System.ServiceModel.PeerSecuritySettings.Transport*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel/PeerSecuritySettings.xml
  ms.technology:
  - dotnet-standard
  manager: ghogen
references:
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.ArgumentOutOfRangeException
  parent: System
  isExternal: false
  name: ArgumentOutOfRangeException
  nameWithType: ArgumentOutOfRangeException
  fullName: System.ArgumentOutOfRangeException
- uid: System.ServiceModel.PeerSecuritySettings.#ctor
  parent: System.ServiceModel.PeerSecuritySettings
  isExternal: false
  name: PeerSecuritySettings()
  nameWithType: PeerSecuritySettings.PeerSecuritySettings()
  fullName: PeerSecuritySettings.PeerSecuritySettings()
- uid: System.ServiceModel.PeerSecuritySettings.Mode
  parent: System.ServiceModel.PeerSecuritySettings
  isExternal: false
  name: Mode
  nameWithType: PeerSecuritySettings.Mode
  fullName: PeerSecuritySettings.Mode
- uid: System.ServiceModel.SecurityMode
  parent: System.ServiceModel
  isExternal: false
  name: SecurityMode
  nameWithType: SecurityMode
  fullName: System.ServiceModel.SecurityMode
- uid: System.ServiceModel.PeerSecuritySettings.ShouldSerializeMode
  parent: System.ServiceModel.PeerSecuritySettings
  isExternal: false
  name: ShouldSerializeMode()
  nameWithType: PeerSecuritySettings.ShouldSerializeMode()
  fullName: PeerSecuritySettings.ShouldSerializeMode()
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ServiceModel.PeerSecuritySettings.ShouldSerializeTransport
  parent: System.ServiceModel.PeerSecuritySettings
  isExternal: false
  name: ShouldSerializeTransport()
  nameWithType: PeerSecuritySettings.ShouldSerializeTransport()
  fullName: PeerSecuritySettings.ShouldSerializeTransport()
- uid: System.ServiceModel.PeerSecuritySettings.Transport
  parent: System.ServiceModel.PeerSecuritySettings
  isExternal: false
  name: Transport
  nameWithType: PeerSecuritySettings.Transport
  fullName: PeerSecuritySettings.Transport
- uid: System.ServiceModel.PeerTransportSecuritySettings
  parent: System.ServiceModel
  isExternal: false
  name: PeerTransportSecuritySettings
  nameWithType: PeerTransportSecuritySettings
  fullName: System.ServiceModel.PeerTransportSecuritySettings
- uid: System.ServiceModel.PeerSecuritySettings.#ctor*
  parent: System.ServiceModel.PeerSecuritySettings
  isExternal: false
  name: PeerSecuritySettings
  nameWithType: PeerSecuritySettings.PeerSecuritySettings
  fullName: PeerSecuritySettings.PeerSecuritySettings
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel/PeerSecuritySettings.xml
- uid: System.ServiceModel.PeerSecuritySettings.Mode*
  parent: System.ServiceModel.PeerSecuritySettings
  isExternal: false
  name: Mode
  nameWithType: PeerSecuritySettings.Mode
  fullName: PeerSecuritySettings.Mode
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel/PeerSecuritySettings.xml
- uid: System.ServiceModel.PeerSecuritySettings.ShouldSerializeMode*
  parent: System.ServiceModel.PeerSecuritySettings
  isExternal: false
  name: ShouldSerializeMode
  nameWithType: PeerSecuritySettings.ShouldSerializeMode
  fullName: PeerSecuritySettings.ShouldSerializeMode
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel/PeerSecuritySettings.xml
- uid: System.ServiceModel.PeerSecuritySettings.ShouldSerializeTransport*
  parent: System.ServiceModel.PeerSecuritySettings
  isExternal: false
  name: ShouldSerializeTransport
  nameWithType: PeerSecuritySettings.ShouldSerializeTransport
  fullName: PeerSecuritySettings.ShouldSerializeTransport
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel/PeerSecuritySettings.xml
- uid: System.ServiceModel.PeerSecuritySettings.Transport*
  parent: System.ServiceModel.PeerSecuritySettings
  isExternal: false
  name: Transport
  nameWithType: PeerSecuritySettings.Transport
  fullName: PeerSecuritySettings.Transport
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel/PeerSecuritySettings.xml
- uid: System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: false
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: Object.Equals(Object)
- uid: System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: false
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: Object.Equals(Object, Object)
- uid: System.Object.GetHashCode
  parent: System.Object
  isExternal: false
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: Object.GetHashCode()
- uid: System.Object.GetType
  parent: System.Object
  isExternal: false
  name: GetType()
  nameWithType: Object.GetType()
  fullName: Object.GetType()
- uid: System.Object.MemberwiseClone
  parent: System.Object
  isExternal: false
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: Object.MemberwiseClone()
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: false
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: Object.ReferenceEquals(Object, Object)
- uid: System.Object.ToString
  parent: System.Object
  isExternal: false
  name: ToString()
  nameWithType: Object.ToString()
  fullName: Object.ToString()
