### YamlMime:ManagedReference
items:
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType
  commentId: T:System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType
  id: PeerApplicationRegistrationType
  children:
  - System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType.AllUsers
  - System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType.CurrentUser
  langs:
  - csharp
  name: PeerApplicationRegistrationType
  nameWithType: PeerApplicationRegistrationType
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType
  type: Enum
  assemblies:
  - System.Net
  namespace: System.Net.PeerToPeer.Collaboration
  summary: Specifies the type of registration to perform for a <xref href="System.Net.PeerToPeer.Collaboration.PeerApplication"></xref> or <xref href="System.Net.PeerToPeer.Collaboration.PeerObject"></xref> registration.
  remarks: Registering an <xref:System.Net.PeerToPeer.Collaboration.PeerApplication> enables it to receive <xref:System.Net.PeerToPeer.Collaboration.PeerCollaboration> invitation requests. The service or application performing the registration must have permission to do so, as it requires access to the <xref:System.Net.PeerToPeer.Collaboration.ContactManager> and other resources like users, applications, and services on the remote machine.
  syntax:
    content: public enum PeerApplicationRegistrationType
  inheritance:
  - System.Object
  - System.ValueType
  - System.Enum
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Net.PeerToPeer.Collaboration/PeerApplicationRegistrationType.xml
  ms.author: bobdel
  manager: markl
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType.AllUsers
  commentId: F:System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType.AllUsers
  id: AllUsers
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType
  langs:
  - csharp
  name: AllUsers
  nameWithType: PeerApplicationRegistrationType.AllUsers
  fullName: PeerApplicationRegistrationType.AllUsers
  type: Field
  assemblies:
  - System.Net
  namespace: System.Net.PeerToPeer.Collaboration
  summary: The <xref href="System.Net.PeerToPeer.Collaboration.PeerApplication"></xref> or <xref href="System.Net.PeerToPeer.Collaboration.PeerObject"></xref> is being registered for all peers of the application host
  syntax:
    content: AllUsers
    return:
      type: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType
      description: ''
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Net.PeerToPeer.Collaboration/PeerApplicationRegistrationType.xml
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType.CurrentUser
  commentId: F:System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType.CurrentUser
  id: CurrentUser
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType
  langs:
  - csharp
  name: CurrentUser
  nameWithType: PeerApplicationRegistrationType.CurrentUser
  fullName: PeerApplicationRegistrationType.CurrentUser
  type: Field
  assemblies:
  - System.Net
  namespace: System.Net.PeerToPeer.Collaboration
  summary: The application or object is being registered only for the user associated with the calling peer
  syntax:
    content: CurrentUser
    return:
      type: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType
      description: ''
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Net.PeerToPeer.Collaboration/PeerApplicationRegistrationType.xml
references:
- uid: System.Enum
  parent: System
  isExternal: false
  name: Enum
  nameWithType: Enum
  fullName: System.Enum
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType.AllUsers
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType
  isExternal: false
  name: AllUsers
  nameWithType: PeerApplicationRegistrationType.AllUsers
  fullName: PeerApplicationRegistrationType.AllUsers
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType
  parent: System.Net.PeerToPeer.Collaboration
  isExternal: false
  name: PeerApplicationRegistrationType
  nameWithType: PeerApplicationRegistrationType
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType.CurrentUser
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType
  isExternal: false
  name: CurrentUser
  nameWithType: PeerApplicationRegistrationType.CurrentUser
  fullName: PeerApplicationRegistrationType.CurrentUser
