### YamlMime:ManagedReference
items:
- uid: System.Deployment.Application.TrustNotGrantedException
  commentId: T:System.Deployment.Application.TrustNotGrantedException
  id: TrustNotGrantedException
  children:
  - System.Deployment.Application.TrustNotGrantedException.#ctor
  - System.Deployment.Application.TrustNotGrantedException.#ctor(System.String)
  - System.Deployment.Application.TrustNotGrantedException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Deployment.Application.TrustNotGrantedException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  name: TrustNotGrantedException
  nameWithType: TrustNotGrantedException
  fullName: System.Deployment.Application.TrustNotGrantedException
  type: Class
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: Indicates that the application does not have the appropriate level of trust to run on the local computer.
  remarks: "By default, [!INCLUDE[ndptecclick](~/includes/ndptecclick-md.md)] applications are given a level of trust on client computers that prevents them from engaging in potentially malicious activity, such as deleting data from the hard drive or accessing the network. A [!INCLUDE[ndptecclick](~/includes/ndptecclick-md.md)] application can use either permission elevation or Trusted Application Deployment to request a higher level of trust:  \n  \n-   Permission elevation asks the user to grant the application a higher level of security.  \n  \n-   Trusted Application Deployment matches the digital signature of the [!INCLUDE[ndptecclick](~/includes/ndptecclick-md.md)] application against a list of trusted publishers on the local machine.  \n  \n <xref:System.Deployment.Application.TrustNotGrantedException> will be thrown if:  \n  \n-   The application uses permission elevation and the user denies the request for elevated trust; or  \n  \n The application uses Trusted Application Deployment and the digital certificate used to sign the application is not listed as a trusted publisher on the local machine.If you have deployed an update to an application, and the update uses more permissions than the previous version, and [!INCLUDE[ndptecclick](~/includes/ndptecclick-md.md)] throws a <xref:System.Deployment.Application.TrustNotGrantedException>, the new version will not install."
  syntax:
    content: 'public class TrustNotGrantedException : System.Deployment.Application.DeploymentException'
  inheritance:
  - System.Object
  - System.Exception
  - System.SystemException
  - System.Deployment.Application.DeploymentException
  implements: []
  inheritedMembers:
  - System.Deployment.Application.DeploymentException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Exception.Data
  - System.Exception.GetBaseException
  - System.Exception.GetType
  - System.Exception.HelpLink
  - System.Exception.HResult
  - System.Exception.InnerException
  - System.Exception.Message
  - System.Exception.SerializeObjectState
  - System.Exception.Source
  - System.Exception.StackTrace
  - System.Exception.TargetSite
  - System.Exception.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Deployment.Application/TrustNotGrantedException.xml
  ms.technology:
  - dotnet-standard
  author: stevehoag
  ms.author: shoag
  manager: wpickett
- uid: System.Deployment.Application.TrustNotGrantedException.#ctor
  commentId: M:System.Deployment.Application.TrustNotGrantedException.#ctor
  id: '#ctor'
  parent: System.Deployment.Application.TrustNotGrantedException
  langs:
  - csharp
  name: TrustNotGrantedException()
  nameWithType: TrustNotGrantedException.TrustNotGrantedException()
  fullName: TrustNotGrantedException.TrustNotGrantedException()
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: Initializes a new instance of the <xref href="System.Deployment.Application.TrustNotGrantedException"></xref> class with a system-supplied message that describes the error.
  remarks: "This constructor initializes the <xref:System.Exception.Message%2A> property of the new instance to a system-supplied message that describes the error, such as \"DefaultMessageDisplayedByParameterlessCtorWriterMustSupply\" This message takes into account the current system culture.  \n  \n The following table shows the initial property values for an instance of <xref:System.InsufficientMemoryException>.  \n  \n|Property|Value|  \n|--------------|-----------|  \n|<xref:System.Exception.InnerException%2A>|`null`.|  \n|<xref:System.Exception.Message%2A>|The localized error message string.|"
  syntax:
    content: public TrustNotGrantedException ();
    parameters: []
  overload: System.Deployment.Application.TrustNotGrantedException.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Deployment.Application/TrustNotGrantedException.xml
  ms.technology:
  - dotnet-standard
  author: stevehoag
  ms.author: shoag
  manager: wpickett
- uid: System.Deployment.Application.TrustNotGrantedException.#ctor(System.String)
  commentId: M:System.Deployment.Application.TrustNotGrantedException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Deployment.Application.TrustNotGrantedException
  langs:
  - csharp
  name: TrustNotGrantedException(String)
  nameWithType: TrustNotGrantedException.TrustNotGrantedException(String)
  fullName: TrustNotGrantedException.TrustNotGrantedException(String)
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: Initializes a new instance of the <xref href="System.Deployment.Application.TrustNotGrantedException"></xref> class with a specified message that describes the error.
  remarks: "The following table shows the initial property values for an instance of <xref:System.Deployment.Application.TrustNotGrantedException>.  \n  \n|Property|Value|  \n|--------------|-----------|  \n|<xref:System.Exception.InnerException%2A>|`null`.|  \n|<xref:System.Exception.Message%2A>|The error message string specified in `message`.|"
  syntax:
    content: public TrustNotGrantedException (string message);
    parameters:
    - id: message
      type: System.String
      description: The message that describes the exception. The caller of this constructor is required to ensure that this string has been localized for the current system culture.
  overload: System.Deployment.Application.TrustNotGrantedException.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Deployment.Application/TrustNotGrantedException.xml
  ms.technology:
  - dotnet-standard
  author: stevehoag
  ms.author: shoag
  manager: wpickett
- uid: System.Deployment.Application.TrustNotGrantedException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  commentId: M:System.Deployment.Application.TrustNotGrantedException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: System.Deployment.Application.TrustNotGrantedException
  langs:
  - csharp
  name: TrustNotGrantedException(SerializationInfo, StreamingContext)
  nameWithType: TrustNotGrantedException.TrustNotGrantedException(SerializationInfo, StreamingContext)
  fullName: TrustNotGrantedException.TrustNotGrantedException(SerializationInfo, StreamingContext)
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: Initializes a new instance of the <xref href="System.Deployment.Application.TrustNotGrantedException"></xref> class with serialized data.
  syntax:
    content: protected TrustNotGrantedException (System.Runtime.Serialization.SerializationInfo serializationInfo, System.Runtime.Serialization.StreamingContext streamingContext);
    parameters:
    - id: serializationInfo
      type: System.Runtime.Serialization.SerializationInfo
      description: The object that holds the serialized object data.
    - id: streamingContext
      type: System.Runtime.Serialization.StreamingContext
      description: The contextual information about the source or destination.
  overload: System.Deployment.Application.TrustNotGrantedException.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Deployment.Application/TrustNotGrantedException.xml
  ms.technology:
  - dotnet-standard
  author: stevehoag
  ms.author: shoag
  manager: wpickett
- uid: System.Deployment.Application.TrustNotGrantedException.#ctor(System.String,System.Exception)
  commentId: M:System.Deployment.Application.TrustNotGrantedException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Deployment.Application.TrustNotGrantedException
  langs:
  - csharp
  name: TrustNotGrantedException(String, Exception)
  nameWithType: TrustNotGrantedException.TrustNotGrantedException(String, Exception)
  fullName: TrustNotGrantedException.TrustNotGrantedException(String, Exception)
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: Initializes a new instance of the <xref href="System.Deployment.Application.TrustNotGrantedException"></xref> class with a specified error message and a reference to the inner exception that is the cause of this exception.
  syntax:
    content: public TrustNotGrantedException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: The message that describes the exception. The caller of this constructor is required to ensure that this string has been localized for the current system culture.
    - id: innerException
      type: System.Exception
      description: The exception that is the cause of the current exception. If the <code>innerException</code> parameter is not `null`, the current exception is raised in a `catch` block that handles the inner exception.
  overload: System.Deployment.Application.TrustNotGrantedException.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Deployment.Application/TrustNotGrantedException.xml
  ms.technology:
  - dotnet-standard
  author: stevehoag
  ms.author: shoag
  manager: wpickett
references:
- uid: System.Deployment.Application.DeploymentException
  parent: System.Deployment.Application
  isExternal: false
  name: DeploymentException
  nameWithType: DeploymentException
  fullName: System.Deployment.Application.DeploymentException
- uid: System.Deployment.Application.TrustNotGrantedException.#ctor
  parent: System.Deployment.Application.TrustNotGrantedException
  isExternal: false
  name: TrustNotGrantedException()
  nameWithType: TrustNotGrantedException.TrustNotGrantedException()
  fullName: TrustNotGrantedException.TrustNotGrantedException()
- uid: System.Deployment.Application.TrustNotGrantedException.#ctor(System.String)
  parent: System.Deployment.Application.TrustNotGrantedException
  isExternal: false
  name: TrustNotGrantedException(String)
  nameWithType: TrustNotGrantedException.TrustNotGrantedException(String)
  fullName: TrustNotGrantedException.TrustNotGrantedException(String)
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Deployment.Application.TrustNotGrantedException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Deployment.Application.TrustNotGrantedException
  isExternal: false
  name: TrustNotGrantedException(SerializationInfo, StreamingContext)
  nameWithType: TrustNotGrantedException.TrustNotGrantedException(SerializationInfo, StreamingContext)
  fullName: TrustNotGrantedException.TrustNotGrantedException(SerializationInfo, StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: false
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.Deployment.Application.TrustNotGrantedException.#ctor(System.String,System.Exception)
  parent: System.Deployment.Application.TrustNotGrantedException
  isExternal: false
  name: TrustNotGrantedException(String, Exception)
  nameWithType: TrustNotGrantedException.TrustNotGrantedException(String, Exception)
  fullName: TrustNotGrantedException.TrustNotGrantedException(String, Exception)
- uid: System.Exception
  parent: System
  isExternal: false
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.Deployment.Application.TrustNotGrantedException.#ctor*
  parent: System.Deployment.Application.TrustNotGrantedException
  isExternal: false
  name: TrustNotGrantedException
  nameWithType: TrustNotGrantedException.TrustNotGrantedException
  fullName: TrustNotGrantedException.TrustNotGrantedException
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Deployment.Application/TrustNotGrantedException.xml
- uid: System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: false
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: Object.Equals(Object)
- uid: System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: false
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: Object.Equals(Object, Object)
- uid: System.Object.GetHashCode
  parent: System.Object
  isExternal: false
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: Object.GetHashCode()
- uid: System.Exception.GetType
  parent: System.Exception
  isExternal: false
  name: GetType()
  nameWithType: Exception.GetType()
  fullName: Exception.GetType()
- uid: System.Object.MemberwiseClone
  parent: System.Object
  isExternal: false
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: Object.MemberwiseClone()
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: false
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: Object.ReferenceEquals(Object, Object)
- uid: System.Exception.ToString
  parent: System.Exception
  isExternal: false
  name: ToString()
  nameWithType: Exception.ToString()
  fullName: Exception.ToString()
- uid: System.Exception.Data
  parent: System.Exception
  isExternal: false
  name: Data
  nameWithType: Exception.Data
  fullName: Exception.Data
- uid: System.Exception.GetBaseException
  parent: System.Exception
  isExternal: false
  name: GetBaseException()
  nameWithType: Exception.GetBaseException()
  fullName: Exception.GetBaseException()
- uid: System.Deployment.Application.DeploymentException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Deployment.Application.DeploymentException
  isExternal: false
  name: GetObjectData(SerializationInfo, StreamingContext)
  nameWithType: DeploymentException.GetObjectData(SerializationInfo, StreamingContext)
  fullName: DeploymentException.GetObjectData(SerializationInfo, StreamingContext)
- uid: System.Exception.HelpLink
  parent: System.Exception
  isExternal: false
  name: HelpLink
  nameWithType: Exception.HelpLink
  fullName: Exception.HelpLink
- uid: System.Exception.HResult
  parent: System.Exception
  isExternal: false
  name: HResult
  nameWithType: Exception.HResult
  fullName: Exception.HResult
- uid: System.Exception.InnerException
  parent: System.Exception
  isExternal: false
  name: InnerException
  nameWithType: Exception.InnerException
  fullName: Exception.InnerException
- uid: System.Exception.Message
  parent: System.Exception
  isExternal: false
  name: Message
  nameWithType: Exception.Message
  fullName: Exception.Message
- uid: System.Exception.SerializeObjectState
  parent: System.Exception
  isExternal: false
  name: SerializeObjectState
  nameWithType: Exception.SerializeObjectState
  fullName: Exception.SerializeObjectState
- uid: System.Exception.Source
  parent: System.Exception
  isExternal: false
  name: Source
  nameWithType: Exception.Source
  fullName: Exception.Source
- uid: System.Exception.StackTrace
  parent: System.Exception
  isExternal: false
  name: StackTrace
  nameWithType: Exception.StackTrace
  fullName: Exception.StackTrace
- uid: System.Exception.TargetSite
  parent: System.Exception
  isExternal: false
  name: TargetSite
  nameWithType: Exception.TargetSite
  fullName: Exception.TargetSite
