### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.Internal.IInternalConfigWebHost
  commentId: T:System.Web.Configuration.Internal.IInternalConfigWebHost
  id: IInternalConfigWebHost
  children:
  - System.Web.Configuration.Internal.IInternalConfigWebHost.GetConfigPathFromSiteIDAndVPath(System.String,System.String)
  - System.Web.Configuration.Internal.IInternalConfigWebHost.GetSiteIDAndVPathFromConfigPath(System.String,System.String@,System.String@)
  langs:
  - csharp
  name: IInternalConfigWebHost
  nameWithType: IInternalConfigWebHost
  fullName: System.Web.Configuration.Internal.IInternalConfigWebHost
  type: Interface
  assemblies:
  - System.Web
  namespace: System.Web.Configuration.Internal
  summary: Defines interfaces used by internal .NET Framework infrastructure for accessing and manipulating Host configuration files.
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(false)]

      public interface IInternalConfigWebHost
  implements: []
  attributes:
  - type: System.Runtime.InteropServices.ComVisibleAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration.Internal/IInternalConfigWebHost.xml
  ms.technology:
  - dotnet-webforms
  author: tdykstra
  ms.author: tdykstra
  manager: wpickett
- uid: System.Web.Configuration.Internal.IInternalConfigWebHost.GetConfigPathFromSiteIDAndVPath(System.String,System.String)
  commentId: M:System.Web.Configuration.Internal.IInternalConfigWebHost.GetConfigPathFromSiteIDAndVPath(System.String,System.String)
  id: GetConfigPathFromSiteIDAndVPath(System.String,System.String)
  parent: System.Web.Configuration.Internal.IInternalConfigWebHost
  langs:
  - csharp
  name: GetConfigPathFromSiteIDAndVPath(String, String)
  nameWithType: IInternalConfigWebHost.GetConfigPathFromSiteIDAndVPath(String, String)
  fullName: IInternalConfigWebHost.GetConfigPathFromSiteIDAndVPath(String, String)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration.Internal
  summary: Returns a value representing the path to a configuration file associated with the provided site identifier and application's virtual path.
  syntax:
    content: public string GetConfigPathFromSiteIDAndVPath (string siteID, string vpath);
    parameters:
    - id: siteID
      type: System.String
      description: The application's site identifier. For more information, see ASP.NET Configuration Overview.
    - id: vpath
      type: System.String
      description: The application's virtual path as a string. For more information, see ASP.NET Web Site Paths.
    return:
      type: System.String
      description: A string representing the path to a configuration file.
  overload: System.Web.Configuration.Internal.IInternalConfigWebHost.GetConfigPathFromSiteIDAndVPath*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration.Internal/IInternalConfigWebHost.xml
  ms.technology:
  - dotnet-webforms
  author: tdykstra
  ms.author: tdykstra
  manager: wpickett
- uid: System.Web.Configuration.Internal.IInternalConfigWebHost.GetSiteIDAndVPathFromConfigPath(System.String,System.String@,System.String@)
  commentId: M:System.Web.Configuration.Internal.IInternalConfigWebHost.GetSiteIDAndVPathFromConfigPath(System.String,System.String@,System.String@)
  id: GetSiteIDAndVPathFromConfigPath(System.String,System.String@,System.String@)
  parent: System.Web.Configuration.Internal.IInternalConfigWebHost
  langs:
  - csharp
  name: GetSiteIDAndVPathFromConfigPath(String, String, String)
  nameWithType: IInternalConfigWebHost.GetSiteIDAndVPathFromConfigPath(String, String, String)
  fullName: IInternalConfigWebHost.GetSiteIDAndVPathFromConfigPath(String, String, String)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration.Internal
  summary: Sets the current site identifier of a configuration object based on the application virtual path and the application configuration path.
  syntax:
    content: public void GetSiteIDAndVPathFromConfigPath (string configPath, out string siteID, out string vpath);
    parameters:
    - id: configPath
      type: System.String
      description: A string representing the path to the application's configuration file.
    - id: siteID
      type: System.String
      description: The application's site Identifier. For more information, see ASP.NET Configuration Overview.
    - id: vpath
      type: System.String
      description: The application's virtual path as a string. For more information, see ASP.NET Web Site Paths.
  overload: System.Web.Configuration.Internal.IInternalConfigWebHost.GetSiteIDAndVPathFromConfigPath*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration.Internal/IInternalConfigWebHost.xml
  ms.technology:
  - dotnet-webforms
  author: tdykstra
  ms.author: tdykstra
  manager: wpickett
references:
- uid: System.Web.Configuration.Internal.IInternalConfigWebHost.GetConfigPathFromSiteIDAndVPath(System.String,System.String)
  parent: System.Web.Configuration.Internal.IInternalConfigWebHost
  isExternal: false
  name: GetConfigPathFromSiteIDAndVPath(String, String)
  nameWithType: IInternalConfigWebHost.GetConfigPathFromSiteIDAndVPath(String, String)
  fullName: IInternalConfigWebHost.GetConfigPathFromSiteIDAndVPath(String, String)
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.Internal.IInternalConfigWebHost.GetSiteIDAndVPathFromConfigPath(System.String,System.String@,System.String@)
  parent: System.Web.Configuration.Internal.IInternalConfigWebHost
  isExternal: false
  name: GetSiteIDAndVPathFromConfigPath(String, String, String)
  nameWithType: IInternalConfigWebHost.GetSiteIDAndVPathFromConfigPath(String, String, String)
  fullName: IInternalConfigWebHost.GetSiteIDAndVPathFromConfigPath(String, String, String)
- uid: System.Web.Configuration.Internal.IInternalConfigWebHost.GetConfigPathFromSiteIDAndVPath*
  parent: System.Web.Configuration.Internal.IInternalConfigWebHost
  isExternal: false
  name: GetConfigPathFromSiteIDAndVPath
  nameWithType: IInternalConfigWebHost.GetConfigPathFromSiteIDAndVPath
  fullName: IInternalConfigWebHost.GetConfigPathFromSiteIDAndVPath
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration.Internal/IInternalConfigWebHost.xml
- uid: System.Web.Configuration.Internal.IInternalConfigWebHost.GetSiteIDAndVPathFromConfigPath*
  parent: System.Web.Configuration.Internal.IInternalConfigWebHost
  isExternal: false
  name: GetSiteIDAndVPathFromConfigPath
  nameWithType: IInternalConfigWebHost.GetSiteIDAndVPathFromConfigPath
  fullName: IInternalConfigWebHost.GetSiteIDAndVPathFromConfigPath
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration.Internal/IInternalConfigWebHost.xml
