### YamlMime:ManagedReference
items:
- uid: System.Windows.BaseValueSource
  commentId: T:System.Windows.BaseValueSource
  id: BaseValueSource
  children:
  - System.Windows.BaseValueSource.Default
  - System.Windows.BaseValueSource.DefaultStyle
  - System.Windows.BaseValueSource.DefaultStyleTrigger
  - System.Windows.BaseValueSource.ImplicitStyleReference
  - System.Windows.BaseValueSource.Inherited
  - System.Windows.BaseValueSource.Local
  - System.Windows.BaseValueSource.ParentTemplate
  - System.Windows.BaseValueSource.ParentTemplateTrigger
  - System.Windows.BaseValueSource.Style
  - System.Windows.BaseValueSource.StyleTrigger
  - System.Windows.BaseValueSource.TemplateTrigger
  - System.Windows.BaseValueSource.Unknown
  langs:
  - csharp
  name: BaseValueSource
  nameWithType: BaseValueSource
  fullName: System.Windows.BaseValueSource
  type: Enum
  assemblies:
  - PresentationFramework
  namespace: System.Windows
  summary: Identifies the property system source of a particular dependency property value.
  remarks: "This enumeration is used by a property within the <xref:System.Windows.ValueSource> structure, which in turn is obtained by calling a <xref:System.Windows.DependencyPropertyHelper.GetValueSource%2A> method against a particular dependency property.  \n  \n Each value of this enumeration indicates that a particular aspect of the overall [!INCLUDE[TLA2#tla_winclient](~/includes/tla2sharptla-winclient-md.md)] property system was responsible for the effective value determination of a certain dependency property value on a specific dependency object. To learn more about the [!INCLUDE[TLA2#tla_winclient](~/includes/tla2sharptla-winclient-md.md)] property system and the precedence at which each aspect of the property system operates, see [Dependency Property Value Precedence](~/docs/framework/wpf/advanced/dependency-property-value-precedence.md).  \n  \n The value Default is not the default value of the enumeration."
  syntax:
    content: public enum BaseValueSource
  inheritance:
  - System.Object
  - System.ValueType
  - System.Enum
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Windows/BaseValueSource.xml
  ms.technology:
  - dotnet-wpf
  ms.author: kempb
  manager: ghogen
- uid: System.Windows.BaseValueSource.Default
  commentId: F:System.Windows.BaseValueSource.Default
  id: Default
  parent: System.Windows.BaseValueSource
  langs:
  - csharp
  name: Default
  nameWithType: BaseValueSource.Default
  fullName: BaseValueSource.Default
  type: Field
  assemblies:
  - PresentationFramework
  namespace: System.Windows
  summary: Source is the default value, as defined by property metadata.
  syntax:
    content: Default
    return:
      type: System.Windows.BaseValueSource
      description: ''
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Windows/BaseValueSource.xml
- uid: System.Windows.BaseValueSource.DefaultStyle
  commentId: F:System.Windows.BaseValueSource.DefaultStyle
  id: DefaultStyle
  parent: System.Windows.BaseValueSource
  langs:
  - csharp
  name: DefaultStyle
  nameWithType: BaseValueSource.DefaultStyle
  fullName: BaseValueSource.DefaultStyle
  type: Field
  assemblies:
  - PresentationFramework
  namespace: System.Windows
  summary: Source is from a setter in the default style. The default style comes from the current theme.
  syntax:
    content: DefaultStyle
    return:
      type: System.Windows.BaseValueSource
      description: ''
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Windows/BaseValueSource.xml
- uid: System.Windows.BaseValueSource.DefaultStyleTrigger
  commentId: F:System.Windows.BaseValueSource.DefaultStyleTrigger
  id: DefaultStyleTrigger
  parent: System.Windows.BaseValueSource
  langs:
  - csharp
  name: DefaultStyleTrigger
  nameWithType: BaseValueSource.DefaultStyleTrigger
  fullName: BaseValueSource.DefaultStyleTrigger
  type: Field
  assemblies:
  - PresentationFramework
  namespace: System.Windows
  summary: Source is from a trigger in the default style. The default style comes from the current theme.
  syntax:
    content: DefaultStyleTrigger
    return:
      type: System.Windows.BaseValueSource
      description: ''
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Windows/BaseValueSource.xml
- uid: System.Windows.BaseValueSource.ImplicitStyleReference
  commentId: F:System.Windows.BaseValueSource.ImplicitStyleReference
  id: ImplicitStyleReference
  parent: System.Windows.BaseValueSource
  langs:
  - csharp
  name: ImplicitStyleReference
  nameWithType: BaseValueSource.ImplicitStyleReference
  fullName: BaseValueSource.ImplicitStyleReference
  type: Field
  assemblies:
  - PresentationFramework
  namespace: System.Windows
  summary: Source is an implicit style reference (style was based on detected type or based type). This value is only returned for the Style property itself, not for properties that are set through setters or triggers of such a style.
  syntax:
    content: ImplicitStyleReference
    return:
      type: System.Windows.BaseValueSource
      description: ''
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Windows/BaseValueSource.xml
- uid: System.Windows.BaseValueSource.Inherited
  commentId: F:System.Windows.BaseValueSource.Inherited
  id: Inherited
  parent: System.Windows.BaseValueSource
  langs:
  - csharp
  name: Inherited
  nameWithType: BaseValueSource.Inherited
  fullName: BaseValueSource.Inherited
  type: Field
  assemblies:
  - PresentationFramework
  namespace: System.Windows
  summary: Source is a value through property value inheritance.
  syntax:
    content: Inherited
    return:
      type: System.Windows.BaseValueSource
      description: ''
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Windows/BaseValueSource.xml
- uid: System.Windows.BaseValueSource.Local
  commentId: F:System.Windows.BaseValueSource.Local
  id: Local
  parent: System.Windows.BaseValueSource
  langs:
  - csharp
  name: Local
  nameWithType: BaseValueSource.Local
  fullName: BaseValueSource.Local
  type: Field
  assemblies:
  - PresentationFramework
  namespace: System.Windows
  summary: Source is a locally set value.
  syntax:
    content: Local
    return:
      type: System.Windows.BaseValueSource
      description: ''
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Windows/BaseValueSource.xml
- uid: System.Windows.BaseValueSource.ParentTemplate
  commentId: F:System.Windows.BaseValueSource.ParentTemplate
  id: ParentTemplate
  parent: System.Windows.BaseValueSource
  langs:
  - csharp
  name: ParentTemplate
  nameWithType: BaseValueSource.ParentTemplate
  fullName: BaseValueSource.ParentTemplate
  type: Field
  assemblies:
  - PresentationFramework
  namespace: System.Windows
  summary: Source is based on a parent template being used by an element.
  syntax:
    content: ParentTemplate
    return:
      type: System.Windows.BaseValueSource
      description: ''
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Windows/BaseValueSource.xml
- uid: System.Windows.BaseValueSource.ParentTemplateTrigger
  commentId: F:System.Windows.BaseValueSource.ParentTemplateTrigger
  id: ParentTemplateTrigger
  parent: System.Windows.BaseValueSource
  langs:
  - csharp
  name: ParentTemplateTrigger
  nameWithType: BaseValueSource.ParentTemplateTrigger
  fullName: BaseValueSource.ParentTemplateTrigger
  type: Field
  assemblies:
  - PresentationFramework
  namespace: System.Windows
  summary: Source is a trigger-based value from a parent template that created the element.
  syntax:
    content: ParentTemplateTrigger
    return:
      type: System.Windows.BaseValueSource
      description: ''
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Windows/BaseValueSource.xml
- uid: System.Windows.BaseValueSource.Style
  commentId: F:System.Windows.BaseValueSource.Style
  id: Style
  parent: System.Windows.BaseValueSource
  langs:
  - csharp
  name: Style
  nameWithType: BaseValueSource.Style
  fullName: BaseValueSource.Style
  type: Field
  assemblies:
  - PresentationFramework
  namespace: System.Windows
  summary: Source is from a style setter of a non-theme style.
  syntax:
    content: Style
    return:
      type: System.Windows.BaseValueSource
      description: ''
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Windows/BaseValueSource.xml
- uid: System.Windows.BaseValueSource.StyleTrigger
  commentId: F:System.Windows.BaseValueSource.StyleTrigger
  id: StyleTrigger
  parent: System.Windows.BaseValueSource
  langs:
  - csharp
  name: StyleTrigger
  nameWithType: BaseValueSource.StyleTrigger
  fullName: BaseValueSource.StyleTrigger
  type: Field
  assemblies:
  - PresentationFramework
  namespace: System.Windows
  summary: Source is a trigger-based value of a non-theme style.
  syntax:
    content: StyleTrigger
    return:
      type: System.Windows.BaseValueSource
      description: ''
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Windows/BaseValueSource.xml
- uid: System.Windows.BaseValueSource.TemplateTrigger
  commentId: F:System.Windows.BaseValueSource.TemplateTrigger
  id: TemplateTrigger
  parent: System.Windows.BaseValueSource
  langs:
  - csharp
  name: TemplateTrigger
  nameWithType: BaseValueSource.TemplateTrigger
  fullName: BaseValueSource.TemplateTrigger
  type: Field
  assemblies:
  - PresentationFramework
  namespace: System.Windows
  summary: Source is a trigger-based value in a template that is from a non-theme style.
  syntax:
    content: TemplateTrigger
    return:
      type: System.Windows.BaseValueSource
      description: ''
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Windows/BaseValueSource.xml
- uid: System.Windows.BaseValueSource.Unknown
  commentId: F:System.Windows.BaseValueSource.Unknown
  id: Unknown
  parent: System.Windows.BaseValueSource
  langs:
  - csharp
  name: Unknown
  nameWithType: BaseValueSource.Unknown
  fullName: BaseValueSource.Unknown
  type: Field
  assemblies:
  - PresentationFramework
  namespace: System.Windows
  summary: Source is not known. This is the default value.
  syntax:
    content: Unknown
    return:
      type: System.Windows.BaseValueSource
      description: ''
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Windows/BaseValueSource.xml
references:
- uid: System.Enum
  parent: System
  isExternal: false
  name: Enum
  nameWithType: Enum
  fullName: System.Enum
- uid: System.Windows.BaseValueSource.Default
  parent: System.Windows.BaseValueSource
  isExternal: false
  name: Default
  nameWithType: BaseValueSource.Default
  fullName: BaseValueSource.Default
- uid: System.Windows.BaseValueSource
  parent: System.Windows
  isExternal: false
  name: BaseValueSource
  nameWithType: BaseValueSource
  fullName: System.Windows.BaseValueSource
- uid: System.Windows.BaseValueSource.DefaultStyle
  parent: System.Windows.BaseValueSource
  isExternal: false
  name: DefaultStyle
  nameWithType: BaseValueSource.DefaultStyle
  fullName: BaseValueSource.DefaultStyle
- uid: System.Windows.BaseValueSource.DefaultStyleTrigger
  parent: System.Windows.BaseValueSource
  isExternal: false
  name: DefaultStyleTrigger
  nameWithType: BaseValueSource.DefaultStyleTrigger
  fullName: BaseValueSource.DefaultStyleTrigger
- uid: System.Windows.BaseValueSource.ImplicitStyleReference
  parent: System.Windows.BaseValueSource
  isExternal: false
  name: ImplicitStyleReference
  nameWithType: BaseValueSource.ImplicitStyleReference
  fullName: BaseValueSource.ImplicitStyleReference
- uid: System.Windows.BaseValueSource.Inherited
  parent: System.Windows.BaseValueSource
  isExternal: false
  name: Inherited
  nameWithType: BaseValueSource.Inherited
  fullName: BaseValueSource.Inherited
- uid: System.Windows.BaseValueSource.Local
  parent: System.Windows.BaseValueSource
  isExternal: false
  name: Local
  nameWithType: BaseValueSource.Local
  fullName: BaseValueSource.Local
- uid: System.Windows.BaseValueSource.ParentTemplate
  parent: System.Windows.BaseValueSource
  isExternal: false
  name: ParentTemplate
  nameWithType: BaseValueSource.ParentTemplate
  fullName: BaseValueSource.ParentTemplate
- uid: System.Windows.BaseValueSource.ParentTemplateTrigger
  parent: System.Windows.BaseValueSource
  isExternal: false
  name: ParentTemplateTrigger
  nameWithType: BaseValueSource.ParentTemplateTrigger
  fullName: BaseValueSource.ParentTemplateTrigger
- uid: System.Windows.BaseValueSource.Style
  parent: System.Windows.BaseValueSource
  isExternal: false
  name: Style
  nameWithType: BaseValueSource.Style
  fullName: BaseValueSource.Style
- uid: System.Windows.BaseValueSource.StyleTrigger
  parent: System.Windows.BaseValueSource
  isExternal: false
  name: StyleTrigger
  nameWithType: BaseValueSource.StyleTrigger
  fullName: BaseValueSource.StyleTrigger
- uid: System.Windows.BaseValueSource.TemplateTrigger
  parent: System.Windows.BaseValueSource
  isExternal: false
  name: TemplateTrigger
  nameWithType: BaseValueSource.TemplateTrigger
  fullName: BaseValueSource.TemplateTrigger
- uid: System.Windows.BaseValueSource.Unknown
  parent: System.Windows.BaseValueSource
  isExternal: false
  name: Unknown
  nameWithType: BaseValueSource.Unknown
  fullName: BaseValueSource.Unknown
