### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Activation.Configuration.Dummy
  commentId: T:System.ServiceModel.Activation.Configuration.Dummy
  id: Dummy
  children:
  - System.ServiceModel.Activation.Configuration.Dummy.#ctor
  langs:
  - csharp
  name: Dummy
  nameWithType: Dummy
  fullName: System.ServiceModel.Activation.Configuration.Dummy
  type: Class
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Activation.Configuration
  syntax:
    content: public class Dummy
  inheritance:
  - System.Object
  implements: []
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - xamarinandroid-7.1
  - xamarinios-10.8
  - xamarinmac-3.0
  monikers:
  - xamarinandroid-7.1
  - xamarinios-10.8
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activation.Configuration/Dummy.xml
- uid: System.ServiceModel.Activation.Configuration.Dummy.#ctor
  commentId: M:System.ServiceModel.Activation.Configuration.Dummy.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Activation.Configuration.Dummy
  langs:
  - csharp
  name: Dummy()
  nameWithType: Dummy.Dummy()
  fullName: Dummy.Dummy()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Activation.Configuration
  syntax:
    content: public Dummy ();
    parameters: []
  overload: System.ServiceModel.Activation.Configuration.Dummy.#ctor*
  exceptions: []
  version:
  - xamarinandroid-7.1
  - xamarinios-10.8
  - xamarinmac-3.0
  monikers:
  - xamarinandroid-7.1
  - xamarinios-10.8
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activation.Configuration/Dummy.xml
references:
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.ServiceModel.Activation.Configuration.Dummy.#ctor
  parent: System.ServiceModel.Activation.Configuration.Dummy
  isExternal: false
  name: Dummy()
  nameWithType: Dummy.Dummy()
  fullName: Dummy.Dummy()
- uid: System.ServiceModel.Activation.Configuration.Dummy.#ctor*
  parent: System.ServiceModel.Activation.Configuration.Dummy
  isExternal: false
  name: Dummy
  nameWithType: Dummy.Dummy
  fullName: Dummy.Dummy
  monikers:
  - xamarinandroid-7.1
  - xamarinios-10.8
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activation.Configuration/Dummy.xml
- uid: System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: false
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: Object.Equals(Object)
- uid: System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: false
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: Object.Equals(Object, Object)
- uid: System.Object.GetHashCode
  parent: System.Object
  isExternal: false
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: Object.GetHashCode()
- uid: System.Object.GetType
  parent: System.Object
  isExternal: false
  name: GetType()
  nameWithType: Object.GetType()
  fullName: Object.GetType()
- uid: System.Object.MemberwiseClone
  parent: System.Object
  isExternal: false
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: Object.MemberwiseClone()
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: false
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: Object.ReferenceEquals(Object, Object)
- uid: System.Object.ToString
  parent: System.Object
  isExternal: false
  name: ToString()
  nameWithType: Object.ToString()
  fullName: Object.ToString()
