### YamlMime:ManagedReference
items:
- uid: System.Security
  id: System.Security
  children:
  - System.Security.AllowPartiallyTrustedCallersAttribute
  - System.Security.CodeAccessPermission
  - System.Security.HostProtectionException
  - System.Security.HostSecurityManager
  - System.Security.HostSecurityManagerOptions
  - System.Security.IEvidenceFactory
  - System.Security.IPermission
  - System.Security.ISecurityEncodable
  - System.Security.ISecurityPolicyEncodable
  - System.Security.IStackWalk
  - System.Security.ManifestKinds
  - System.Security.NamedPermissionSet
  - System.Security.PartialTrustVisibilityLevel
  - System.Security.PermissionSet
  - System.Security.PolicyLevelType
  - System.Security.ReadOnlyPermissionSet
  - System.Security.SecureString
  - System.Security.SecureStringMarshal
  - System.Security.SecurityContext
  - System.Security.SecurityContextSource
  - System.Security.SecurityCriticalAttribute
  - System.Security.SecurityCriticalScope
  - System.Security.SecurityElement
  - System.Security.SecurityException
  - System.Security.SecurityManager
  - System.Security.SecurityRulesAttribute
  - System.Security.SecurityRuleSet
  - System.Security.SecuritySafeCriticalAttribute
  - System.Security.SecurityState
  - System.Security.SecurityTransparentAttribute
  - System.Security.SecurityTreatAsSafeAttribute
  - System.Security.SecurityZone
  - System.Security.SuppressUnmanagedCodeSecurityAttribute
  - System.Security.UnverifiableCodeAttribute
  - System.Security.VerificationException
  - System.Security.XmlSyntaxException
  langs:
  - csharp
  name: System.Security
  nameWithType: System.Security
  fullName: System.Security
  type: Namespace
  summary: The <xref href="System.Security"></xref> namespace provides the underlying structure of the common language runtime security system, including base classes for permissions.
  version:
  - netcore-1.0
  - netcore-1.1
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - netstandard-1.0
  - netstandard-1.1
  - netstandard-1.2
  - netstandard-1.3
  - netstandard-1.4
  - netstandard-1.5
  - netstandard-1.6
  - netstandard-2.0
  - xamarinandroid-7.1
  - xamarinios-10.8
  - xamarinmac-3.0
  monikers:
  - netcore-1.0
  - netcore-1.1
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - netstandard-1.0
  - netstandard-1.1
  - netstandard-1.2
  - netstandard-1.3
  - netstandard-1.4
  - netstandard-1.5
  - netstandard-1.6
  - netstandard-2.0
  - xamarinandroid-7.1
  - xamarinios-10.8
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/ns-System.Security.xml
  ms.technology:
  - dotnet-standard
  author: mairaw
  ms.author: mairaw
  manager: wpickett
references:
- uid: System.Security.AllowPartiallyTrustedCallersAttribute
  parent: System.Security
  isExternal: false
  name: AllowPartiallyTrustedCallersAttribute
  nameWithType: AllowPartiallyTrustedCallersAttribute
  fullName: System.Security.AllowPartiallyTrustedCallersAttribute
- uid: System.Security.CodeAccessPermission
  parent: System.Security
  isExternal: false
  name: CodeAccessPermission
  nameWithType: CodeAccessPermission
  fullName: System.Security.CodeAccessPermission
- uid: System.Security.HostProtectionException
  parent: System.Security
  isExternal: false
  name: HostProtectionException
  nameWithType: HostProtectionException
  fullName: System.Security.HostProtectionException
- uid: System.Security.HostSecurityManager
  parent: System.Security
  isExternal: false
  name: HostSecurityManager
  nameWithType: HostSecurityManager
  fullName: System.Security.HostSecurityManager
- uid: System.Security.HostSecurityManagerOptions
  parent: System.Security
  isExternal: false
  name: HostSecurityManagerOptions
  nameWithType: HostSecurityManagerOptions
  fullName: System.Security.HostSecurityManagerOptions
- uid: System.Security.IEvidenceFactory
  parent: System.Security
  isExternal: false
  name: IEvidenceFactory
  nameWithType: IEvidenceFactory
  fullName: System.Security.IEvidenceFactory
- uid: System.Security.IPermission
  parent: System.Security
  isExternal: false
  name: IPermission
  nameWithType: IPermission
  fullName: System.Security.IPermission
- uid: System.Security.ISecurityEncodable
  parent: System.Security
  isExternal: false
  name: ISecurityEncodable
  nameWithType: ISecurityEncodable
  fullName: System.Security.ISecurityEncodable
- uid: System.Security.ISecurityPolicyEncodable
  parent: System.Security
  isExternal: false
  name: ISecurityPolicyEncodable
  nameWithType: ISecurityPolicyEncodable
  fullName: System.Security.ISecurityPolicyEncodable
- uid: System.Security.IStackWalk
  parent: System.Security
  isExternal: false
  name: IStackWalk
  nameWithType: IStackWalk
  fullName: System.Security.IStackWalk
- uid: System.Security.ManifestKinds
  parent: System.Security
  isExternal: false
  name: ManifestKinds
  nameWithType: ManifestKinds
  fullName: System.Security.ManifestKinds
- uid: System.Security.NamedPermissionSet
  parent: System.Security
  isExternal: false
  name: NamedPermissionSet
  nameWithType: NamedPermissionSet
  fullName: System.Security.NamedPermissionSet
- uid: System.Security.PartialTrustVisibilityLevel
  parent: System.Security
  isExternal: false
  name: PartialTrustVisibilityLevel
  nameWithType: PartialTrustVisibilityLevel
  fullName: System.Security.PartialTrustVisibilityLevel
- uid: System.Security.PermissionSet
  parent: System.Security
  isExternal: false
  name: PermissionSet
  nameWithType: PermissionSet
  fullName: System.Security.PermissionSet
- uid: System.Security.PolicyLevelType
  parent: System.Security
  isExternal: false
  name: PolicyLevelType
  nameWithType: PolicyLevelType
  fullName: System.Security.PolicyLevelType
- uid: System.Security.ReadOnlyPermissionSet
  parent: System.Security
  isExternal: false
  name: ReadOnlyPermissionSet
  nameWithType: ReadOnlyPermissionSet
  fullName: System.Security.ReadOnlyPermissionSet
- uid: System.Security.SecureString
  parent: System.Security
  isExternal: false
  name: SecureString
  nameWithType: SecureString
  fullName: System.Security.SecureString
- uid: System.Security.SecureStringMarshal
  parent: System.Security
  isExternal: false
  name: SecureStringMarshal
  nameWithType: SecureStringMarshal
  fullName: System.Security.SecureStringMarshal
- uid: System.Security.SecurityContext
  parent: System.Security
  isExternal: false
  name: SecurityContext
  nameWithType: SecurityContext
  fullName: System.Security.SecurityContext
- uid: System.Security.SecurityContextSource
  parent: System.Security
  isExternal: false
  name: SecurityContextSource
  nameWithType: SecurityContextSource
  fullName: System.Security.SecurityContextSource
- uid: System.Security.SecurityCriticalAttribute
  parent: System.Security
  isExternal: false
  name: SecurityCriticalAttribute
  nameWithType: SecurityCriticalAttribute
  fullName: System.Security.SecurityCriticalAttribute
- uid: System.Security.SecurityCriticalScope
  parent: System.Security
  isExternal: false
  name: SecurityCriticalScope
  nameWithType: SecurityCriticalScope
  fullName: System.Security.SecurityCriticalScope
- uid: System.Security.SecurityElement
  parent: System.Security
  isExternal: false
  name: SecurityElement
  nameWithType: SecurityElement
  fullName: System.Security.SecurityElement
- uid: System.Security.SecurityException
  parent: System.Security
  isExternal: false
  name: SecurityException
  nameWithType: SecurityException
  fullName: System.Security.SecurityException
- uid: System.Security.SecurityManager
  parent: System.Security
  isExternal: false
  name: SecurityManager
  nameWithType: SecurityManager
  fullName: System.Security.SecurityManager
- uid: System.Security.SecurityRulesAttribute
  parent: System.Security
  isExternal: false
  name: SecurityRulesAttribute
  nameWithType: SecurityRulesAttribute
  fullName: System.Security.SecurityRulesAttribute
- uid: System.Security.SecurityRuleSet
  parent: System.Security
  isExternal: false
  name: SecurityRuleSet
  nameWithType: SecurityRuleSet
  fullName: System.Security.SecurityRuleSet
- uid: System.Security.SecuritySafeCriticalAttribute
  parent: System.Security
  isExternal: false
  name: SecuritySafeCriticalAttribute
  nameWithType: SecuritySafeCriticalAttribute
  fullName: System.Security.SecuritySafeCriticalAttribute
- uid: System.Security.SecurityState
  parent: System.Security
  isExternal: false
  name: SecurityState
  nameWithType: SecurityState
  fullName: System.Security.SecurityState
- uid: System.Security.SecurityTransparentAttribute
  parent: System.Security
  isExternal: false
  name: SecurityTransparentAttribute
  nameWithType: SecurityTransparentAttribute
  fullName: System.Security.SecurityTransparentAttribute
- uid: System.Security.SecurityTreatAsSafeAttribute
  parent: System.Security
  isExternal: false
  name: SecurityTreatAsSafeAttribute
  nameWithType: SecurityTreatAsSafeAttribute
  fullName: System.Security.SecurityTreatAsSafeAttribute
- uid: System.Security.SecurityZone
  parent: System.Security
  isExternal: false
  name: SecurityZone
  nameWithType: SecurityZone
  fullName: System.Security.SecurityZone
- uid: System.Security.SuppressUnmanagedCodeSecurityAttribute
  parent: System.Security
  isExternal: false
  name: SuppressUnmanagedCodeSecurityAttribute
  nameWithType: SuppressUnmanagedCodeSecurityAttribute
  fullName: System.Security.SuppressUnmanagedCodeSecurityAttribute
- uid: System.Security.UnverifiableCodeAttribute
  parent: System.Security
  isExternal: false
  name: UnverifiableCodeAttribute
  nameWithType: UnverifiableCodeAttribute
  fullName: System.Security.UnverifiableCodeAttribute
- uid: System.Security.VerificationException
  parent: System.Security
  isExternal: false
  name: VerificationException
  nameWithType: VerificationException
  fullName: System.Security.VerificationException
- uid: System.Security.XmlSyntaxException
  parent: System.Security
  isExternal: false
  name: XmlSyntaxException
  nameWithType: XmlSyntaxException
  fullName: System.Security.XmlSyntaxException
