### YamlMime:ManagedReference
items:
- uid: System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter
  commentId: T:System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter
  id: ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter
  children:
  - System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult
  - System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.IsCompleted
  - System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.OnCompleted(System.Action)
  - System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.UnsafeOnCompleted(System.Action)
  langs:
  - csharp
  name: ConfiguredValueTaskAwaitable<TResult>.ConfiguredValueTaskAwaiter
  nameWithType: ConfiguredValueTaskAwaitable<TResult>.ConfiguredValueTaskAwaiter
  fullName: System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable<TResult>.ConfiguredValueTaskAwaiter
  type: Struct
  assemblies:
  - System.Threading.Tasks.Extensions
  namespace: System.Runtime.CompilerServices
  syntax:
    content: 'public struct ConfiguredValueTaskAwaitable<TResult>.ConfiguredValueTaskAwaiter : System.Runtime.CompilerServices.ICriticalNotifyCompletion'
    typeParameters:
    - id: TResult
      description: ''
  inheritance:
  - System.Object
  - System.ValueType
  implements:
  - System.Runtime.CompilerServices.ICriticalNotifyCompletion
  version:
  - netcore-1.0
  - netcore-1.1
  - netcore-2.0
  monikers:
  - netcore-1.0
  - netcore-1.1
  - netcore-2.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Runtime.CompilerServices/ConfiguredValueTaskAwaitable`1+ConfiguredValueTaskAwaiter.xml
- uid: System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult
  commentId: M:System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult
  id: GetResult
  parent: System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter
  langs:
  - csharp
  name: GetResult()
  nameWithType: ConfiguredValueTaskAwaitable<TResult>.ConfiguredValueTaskAwaiter.GetResult()
  fullName: ConfiguredValueTaskAwaitable<TResult>.ConfiguredValueTaskAwaiter.GetResult()
  type: Method
  assemblies:
  - System.Threading.Tasks.Extensions
  namespace: System.Runtime.CompilerServices
  syntax:
    content: public TResult GetResult ();
    parameters: []
    return:
      type: TResult
      description: ''
  overload: System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult*
  exceptions: []
  version:
  - netcore-1.0
  - netcore-1.1
  - netcore-2.0
  monikers:
  - netcore-1.0
  - netcore-1.1
  - netcore-2.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Runtime.CompilerServices/ConfiguredValueTaskAwaitable`1+ConfiguredValueTaskAwaiter.xml
- uid: System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.IsCompleted
  commentId: P:System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.IsCompleted
  id: IsCompleted
  parent: System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter
  langs:
  - csharp
  name: IsCompleted
  nameWithType: ConfiguredValueTaskAwaitable<TResult>.ConfiguredValueTaskAwaiter.IsCompleted
  fullName: ConfiguredValueTaskAwaitable<TResult>.ConfiguredValueTaskAwaiter.IsCompleted
  type: Property
  assemblies:
  - System.Threading.Tasks.Extensions
  namespace: System.Runtime.CompilerServices
  syntax:
    content: public bool IsCompleted { get; }
    return:
      type: System.Boolean
      description: ''
  overload: System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.IsCompleted*
  exceptions: []
  version:
  - netcore-1.0
  - netcore-1.1
  - netcore-2.0
  monikers:
  - netcore-1.0
  - netcore-1.1
  - netcore-2.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Runtime.CompilerServices/ConfiguredValueTaskAwaitable`1+ConfiguredValueTaskAwaiter.xml
- uid: System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.OnCompleted(System.Action)
  commentId: M:System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.OnCompleted(System.Action)
  id: OnCompleted(System.Action)
  parent: System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter
  langs:
  - csharp
  name: OnCompleted(Action)
  nameWithType: ConfiguredValueTaskAwaitable<TResult>.ConfiguredValueTaskAwaiter.OnCompleted(Action)
  fullName: ConfiguredValueTaskAwaitable<TResult>.ConfiguredValueTaskAwaiter.OnCompleted(Action)
  type: Method
  assemblies:
  - System.Threading.Tasks.Extensions
  namespace: System.Runtime.CompilerServices
  syntax:
    content: public void OnCompleted (Action continuation);
    parameters:
    - id: continuation
      type: System.Action
      description: ''
  overload: System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.OnCompleted*
  exceptions: []
  version:
  - netcore-1.0
  - netcore-1.1
  - netcore-2.0
  monikers:
  - netcore-1.0
  - netcore-1.1
  - netcore-2.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Runtime.CompilerServices/ConfiguredValueTaskAwaitable`1+ConfiguredValueTaskAwaiter.xml
- uid: System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.UnsafeOnCompleted(System.Action)
  commentId: M:System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.UnsafeOnCompleted(System.Action)
  id: UnsafeOnCompleted(System.Action)
  parent: System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter
  langs:
  - csharp
  name: UnsafeOnCompleted(Action)
  nameWithType: ConfiguredValueTaskAwaitable<TResult>.ConfiguredValueTaskAwaiter.UnsafeOnCompleted(Action)
  fullName: ConfiguredValueTaskAwaitable<TResult>.ConfiguredValueTaskAwaiter.UnsafeOnCompleted(Action)
  type: Method
  assemblies:
  - System.Threading.Tasks.Extensions
  namespace: System.Runtime.CompilerServices
  syntax:
    content: public void UnsafeOnCompleted (Action continuation);
    parameters:
    - id: continuation
      type: System.Action
      description: ''
  overload: System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.UnsafeOnCompleted*
  exceptions: []
  version:
  - netcore-1.0
  - netcore-1.1
  - netcore-2.0
  monikers:
  - netcore-1.0
  - netcore-1.1
  - netcore-2.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Runtime.CompilerServices/ConfiguredValueTaskAwaitable`1+ConfiguredValueTaskAwaiter.xml
references:
- uid: System.ValueType
  parent: System
  isExternal: false
  name: ValueType
  nameWithType: ValueType
  fullName: System.ValueType
- uid: System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult
  parent: System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter
  isExternal: false
  name: GetResult()
  nameWithType: ConfiguredValueTaskAwaitable<TResult>.ConfiguredValueTaskAwaiter.GetResult()
  fullName: ConfiguredValueTaskAwaitable<TResult>.ConfiguredValueTaskAwaiter.GetResult()
- uid: TResult
  isExternal: true
  name: TResult
  nameWithType: TResult
  fullName: TResult
- uid: System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.IsCompleted
  parent: System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter
  isExternal: false
  name: IsCompleted
  nameWithType: ConfiguredValueTaskAwaitable<TResult>.ConfiguredValueTaskAwaiter.IsCompleted
  fullName: ConfiguredValueTaskAwaitable<TResult>.ConfiguredValueTaskAwaiter.IsCompleted
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.OnCompleted(System.Action)
  parent: System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter
  isExternal: false
  name: OnCompleted(Action)
  nameWithType: ConfiguredValueTaskAwaitable<TResult>.ConfiguredValueTaskAwaiter.OnCompleted(Action)
  fullName: ConfiguredValueTaskAwaitable<TResult>.ConfiguredValueTaskAwaiter.OnCompleted(Action)
- uid: System.Action
  parent: System
  isExternal: false
  name: Action
  nameWithType: Action
  fullName: System.Action
- uid: System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.UnsafeOnCompleted(System.Action)
  parent: System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter
  isExternal: false
  name: UnsafeOnCompleted(Action)
  nameWithType: ConfiguredValueTaskAwaitable<TResult>.ConfiguredValueTaskAwaiter.UnsafeOnCompleted(Action)
  fullName: ConfiguredValueTaskAwaitable<TResult>.ConfiguredValueTaskAwaiter.UnsafeOnCompleted(Action)
- uid: System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult*
  parent: System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter
  isExternal: false
  name: GetResult
  nameWithType: ConfiguredValueTaskAwaitable<TResult>.ConfiguredValueTaskAwaiter.GetResult
  fullName: ConfiguredValueTaskAwaitable<TResult>.ConfiguredValueTaskAwaiter.GetResult
  monikers:
  - netcore-1.0
  - netcore-1.1
  - netcore-2.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Runtime.CompilerServices/ConfiguredValueTaskAwaitable`1+ConfiguredValueTaskAwaiter.xml
- uid: System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.IsCompleted*
  parent: System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter
  isExternal: false
  name: IsCompleted
  nameWithType: ConfiguredValueTaskAwaitable<TResult>.ConfiguredValueTaskAwaiter.IsCompleted
  fullName: ConfiguredValueTaskAwaitable<TResult>.ConfiguredValueTaskAwaiter.IsCompleted
  monikers:
  - netcore-1.0
  - netcore-1.1
  - netcore-2.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Runtime.CompilerServices/ConfiguredValueTaskAwaitable`1+ConfiguredValueTaskAwaiter.xml
- uid: System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.OnCompleted*
  parent: System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter
  isExternal: false
  name: OnCompleted
  nameWithType: ConfiguredValueTaskAwaitable<TResult>.ConfiguredValueTaskAwaiter.OnCompleted
  fullName: ConfiguredValueTaskAwaitable<TResult>.ConfiguredValueTaskAwaiter.OnCompleted
  monikers:
  - netcore-1.0
  - netcore-1.1
  - netcore-2.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Runtime.CompilerServices/ConfiguredValueTaskAwaitable`1+ConfiguredValueTaskAwaiter.xml
- uid: System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.UnsafeOnCompleted*
  parent: System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter
  isExternal: false
  name: UnsafeOnCompleted
  nameWithType: ConfiguredValueTaskAwaitable<TResult>.ConfiguredValueTaskAwaiter.UnsafeOnCompleted
  fullName: ConfiguredValueTaskAwaitable<TResult>.ConfiguredValueTaskAwaiter.UnsafeOnCompleted
  monikers:
  - netcore-1.0
  - netcore-1.1
  - netcore-2.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Runtime.CompilerServices/ConfiguredValueTaskAwaitable`1+ConfiguredValueTaskAwaiter.xml
- uid: System.Runtime.CompilerServices.ICriticalNotifyCompletion
  parent: System.Runtime.CompilerServices
  isExternal: false
  name: ICriticalNotifyCompletion
  nameWithType: ICriticalNotifyCompletion
  fullName: System.Runtime.CompilerServices.ICriticalNotifyCompletion
