### YamlMime:ManagedReference
items:
- uid: System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1
  commentId: T:System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1
  id: ConfiguredValueTaskAwaitable`1
  children:
  - System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.GetAwaiter
  langs:
  - csharp
  name: ConfiguredValueTaskAwaitable<TResult>
  nameWithType: ConfiguredValueTaskAwaitable<TResult>
  fullName: System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable<TResult>
  type: Struct
  assemblies:
  - System.Threading.Tasks.Extensions
  namespace: System.Runtime.CompilerServices
  syntax:
    content: public struct ConfiguredValueTaskAwaitable<TResult>
    typeParameters:
    - id: TResult
      description: ''
  inheritance:
  - System.Object
  - System.ValueType
  implements: []
  version:
  - netcore-1.0
  - netcore-1.1
  - netcore-2.0
  monikers:
  - netcore-1.0
  - netcore-1.1
  - netcore-2.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Runtime.CompilerServices/ConfiguredValueTaskAwaitable`1.xml
- uid: System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.GetAwaiter
  commentId: M:System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.GetAwaiter
  id: GetAwaiter
  parent: System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1
  langs:
  - csharp
  name: GetAwaiter()
  nameWithType: ConfiguredValueTaskAwaitable<TResult>.GetAwaiter()
  fullName: ConfiguredValueTaskAwaitable<TResult>.GetAwaiter()
  type: Method
  assemblies:
  - System.Threading.Tasks.Extensions
  namespace: System.Runtime.CompilerServices
  syntax:
    content: public System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable<TResult>.ConfiguredValueTaskAwaiter GetAwaiter ();
    parameters: []
    return:
      type: System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable{TResult}
      description: ''
  overload: System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.GetAwaiter*
  exceptions: []
  version:
  - netcore-1.0
  - netcore-1.1
  - netcore-2.0
  monikers:
  - netcore-1.0
  - netcore-1.1
  - netcore-2.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Runtime.CompilerServices/ConfiguredValueTaskAwaitable`1.xml
references:
- uid: System.ValueType
  parent: System
  isExternal: false
  name: ValueType
  nameWithType: ValueType
  fullName: System.ValueType
- uid: System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.GetAwaiter
  parent: System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1
  isExternal: false
  name: GetAwaiter()
  nameWithType: ConfiguredValueTaskAwaitable<TResult>.GetAwaiter()
  fullName: ConfiguredValueTaskAwaitable<TResult>.GetAwaiter()
- uid: System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1
  name: ConfiguredValueTaskAwaitable<TResult>
  nameWithType: ConfiguredValueTaskAwaitable<TResult>
  fullName: System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable<TResult>
- uid: TResult
  name: TResult
  nameWithType: TResult
  fullName: TResult
- uid: System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable{TResult}
  parent: System.Runtime.CompilerServices
  isExternal: false
  name: ConfiguredValueTaskAwaitable<TResult>
  nameWithType: ConfiguredValueTaskAwaitable<TResult>
  fullName: System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable<TResult>+ConfiguredValueTaskAwaiter
  spec.csharp:
  - uid: System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1
    name: ConfiguredValueTaskAwaitable
    nameWithType: ConfiguredValueTaskAwaitable
    fullName: System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable
  - name: <
    nameWithType: <
    fullName: <
  - uid: TResult
    name: TResult
    nameWithType: TResult
    fullName: TResult
  - name: '>'
    nameWithType: '>'
    fullName: '>'
- uid: System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.GetAwaiter*
  parent: System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1
  isExternal: false
  name: GetAwaiter
  nameWithType: ConfiguredValueTaskAwaitable<TResult>.GetAwaiter
  fullName: ConfiguredValueTaskAwaitable<TResult>.GetAwaiter
  monikers:
  - netcore-1.0
  - netcore-1.1
  - netcore-2.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Runtime.CompilerServices/ConfiguredValueTaskAwaitable`1.xml
